# Generated by Django 5.1.7 on 2025-03-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('pemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
