# Generated by Django 5.1.7 on 2025-04-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_subscrib'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscrib',
        ),
    ]
